### ISSUE TITLE
`hello_embed.rs` not working with `freeze-stdlib` feature

### ISSUE THREAD

**Issue by PitiBouchon** [RustPython/RustPython#5048]
## Summary

The example `hello_embed.rs` does not work (but does with stdlib)

The `hello_embed.rs` :
```rust
fn main() -> rustpython::vm::PyResult<()> {
    rustpython::vm::Interpreter::without_stdlib(Default::default()).enter(|vm| {
        let scope = vm.new_scope_with_builtins();
        let source = r#"print("Hello World!")"#;
        let code_obj = vm
            .compile(source, rustpython::vm::compiler::Mode::Exec, "<embedded>".to_owned())
            .map_err(|err| vm.new_syntax_error(&err, Some(source)))?;

        vm.run_code_obj(code_obj, scope)?;

        Ok(())
    })
}
```
The `Cargo.toml` file :
```toml
[dependencies]
rustpython = { git = "https://github.com/RustPython/RustPython.git", features = ["freeze-stdlib"] }
```

## Error

The error I get with backtrace :
```
lost sys.stderr
RuntimeError: lost sys.stderr
Original exception was:
lost sys.stderr
ImportError: No such frozen object named codecs
[...]
```
